### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by felixakiragreen** [felixakiragreen/artsee#10]
Shortcuts:
- Arrows Keys
- Full-screen

**Comment by milesj76** [comment]
Left - Previous
Right - Next
[ - First
] - Last
F - Full-screen
Spacebar - Random NFT
Esc - Exit full-screen

**Comment by milesj76** [comment]
### Added keyboard shortcuts as a feature to artsee.

Created a new `KeyboardShortcuts` component in order to listen to the window for keydown events. I've kept the logic to determine which key has been pressed inside the component. I created a "dispatch" inside the `Frame` component in order to reuse the UI control functions. I used props instead of moving all the logic to a store because I don't see any reason why another component might use the UI controls or keyboard shortcuts anytime soon. It made it a little simpler to not redo some of the code there that keeps track of the index and most recent fetch.

**Here are the controls I've added:**

_ArrowLeft_ - Previous
_ArrowRight_ - Next
_[_ - First
_]_ - Last
_F_ - Full-screen
_Spacebar_ - Random NFT
_Escape_ - Exit full-screen

When the `Settings` menu is open:

_Escape_ - Hide settings menu
_No other controls should work while the `Settings` menu is open._

The controls all worked when I tested them. Let me know if there's anything I should change.
